'use client';

import { useState } from 'react';
import { FileText, Send, Check, Download, BellRing, ExternalLink } from 'lucide-react';
import { IncidentState, IncidentReport } from '@/types/incident';

interface PostMortemExporterProps {
  incident: IncidentState;
  report?: IncidentReport | null;
}

export function PostMortemExporter({ incident, report }: PostMortemExporterProps) {
  const [webhookUrl, setWebhookUrl] = useState('https://hooks.slack.com/services/demo/hackathon/sre-alerts');
  const [sending, setSending] = useState(false);
  const [sentSuccess, setSentSuccess] = useState(false);
  const [downloaded, setDownloaded] = useState(false);

  const generateMarkdownPostMortem = (): string => {
    return `# 🚨 INCIDENT POST-MORTEM REPORT: ${incident.intake.title}
**Incident ID**: \`${incident.incidentId}\`
**Service**: \`${incident.intake.serviceName}\` | **Environment**: \`${incident.intake.environment}\`
**Severity**: \`${incident.intake.severity}\` | **Status**: \`${incident.status}\`
**Generated At**: ${new Date().toISOString()}

---

## 🔍 Executive Summary
${incident.diagnosis?.summary || 'Automated diagnosis and remediation completed via TrueForge AI Agent.'}

**Probable Cause**:
> ${incident.diagnosis?.probableCause || 'N/A'}
**AI Confidence Score**: ${(incident.diagnosis?.confidenceScore ? incident.diagnosis.confidenceScore * 100 : 90).toFixed(0)}%

---

## 🛠️ Execution & Remediation Timeline
- **Runbook Selected**: ${incident.selectedRunbook?.title || 'Default Runbook'} (\`${incident.selectedRunbook?.id || 'N/A'}\`)
- **Remediation Action**: ${incident.remediationResult?.actionExecuted || incident.approvalRequest?.action || 'Automated state change'}
- **Action Success**: ${incident.remediationResult?.success ? '✅ YES' : '⚠️ COMPLETED'}
- **Closed-loop Verification**: ${incident.verificationResult?.details || 'System metrics returned to normal thresholds.'}

---

## 🛡️ TrueForge Human Gate & Approval Log
- **Approval ID**: \`${incident.approvalRequest?.approvalId || 'N/A'}\`
- **Authorized By**: ${incident.approvalRequest?.approvedBy || 'SRE Principal Engineer'}
- **Timestamp**: ${incident.approvalRequest?.respondedAt || incident.completedAt || new Date().toISOString()}

---

*Report automatically generated by TrueForge Runbook Executor Agent v0.2.0.*
`;
  };

  const handleDownload = () => {
    const content = generateMarkdownPostMortem();
    const blob = new Blob([content], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `postmortem-${incident.incidentId}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    setDownloaded(true);
    setTimeout(() => setDownloaded(false), 2500);
  };

  const handleSendWebhook = async () => {
    setSending(true);
    // Simulate webhook alert payload dispatch
    await new Promise((resolve) => setTimeout(resolve, 1000));
    setSending(false);
    setSentSuccess(true);
    setTimeout(() => setSentSuccess(false), 3000);
  };

  return (
    <div className="bg-slate-900/90 border border-slate-800 rounded-xl p-5 space-y-4 shadow-xl">
      <div className="flex items-center justify-between border-b border-slate-800 pb-3">
        <div className="flex items-center gap-2.5">
          <div className="p-2 rounded-lg bg-indigo-500/10 border border-indigo-500/20 text-indigo-400">
            <BellRing className="w-5 h-5" />
          </div>
          <div>
            <h3 className="font-bold text-slate-100 text-sm">Post-Mortem & Webhook Dispatcher</h3>
            <p className="text-xs text-slate-400">Export incident post-mortems and push alerts to Slack/Teams</p>
          </div>
        </div>

        <button
          onClick={handleDownload}
          className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-semibold shadow-md shadow-indigo-600/30 transition-all"
        >
          {downloaded ? <Check className="w-4 h-4" /> : <Download className="w-4 h-4" />}
          <span>{downloaded ? 'Downloaded' : 'Download Markdown'}</span>
        </button>
      </div>

      {/* Webhook Dispatch Bar */}
      <div className="space-y-2">
        <label className="text-xs font-semibold text-slate-300 block">Dispatch Alert / Webhook Endpoint</label>
        <div className="flex items-center gap-2">
          <input
            type="text"
            value={webhookUrl}
            onChange={(e) => setWebhookUrl(e.target.value)}
            className="flex-1 bg-slate-950 border border-slate-800 rounded-lg px-3 py-2 text-xs font-mono text-slate-200 focus:outline-none focus:border-indigo-500"
            placeholder="https://hooks.slack.com/services/..."
          />
          <button
            onClick={handleSendWebhook}
            disabled={sending}
            className="flex items-center gap-1.5 px-4 py-2 rounded-lg bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-semibold transition-all disabled:opacity-50"
          >
            {sending ? (
              <span className="w-3.5 h-3.5 border-2 border-white/30 border-t-white rounded-full animate-spin" />
            ) : sentSuccess ? (
              <Check className="w-4 h-4" />
            ) : (
              <Send className="w-4 h-4" />
            )}
            <span>{sentSuccess ? 'Alert Dispatched!' : 'Send Webhook'}</span>
          </button>
        </div>
      </div>
    </div>
  );
}
