'use client';

import { useState, useEffect } from 'react';
import { IncidentState, IncidentReport } from '@/types/incident';
import { IncidentService } from '@/services/incident-service';
import { FileText, Download, Terminal, RefreshCw, Copy, Check } from 'lucide-react';

export default function ReportsPage() {
  const [incidents, setIncidents] = useState<IncidentState[]>([]);
  const [selectedIncidentId, setSelectedIncidentId] = useState<string>('');
  const [report, setReport] = useState<IncidentReport | null>(null);
  const [loading, setLoading] = useState(true);
  const [activeTab, setActiveTab] = useState<'VISUAL' | 'MARKDOWN' | 'JSON'>('VISUAL');
  const [copied, setCopied] = useState(false);

  const fetchReportsList = async () => {
    setLoading(true);
    const { incidents: data } = await IncidentService.getAllIncidents();
    setIncidents(data);
    if (data.length > 0) {
      const defaultId = data[0].incidentId;
      setSelectedIncidentId(defaultId);
      const { report: rep } = await IncidentService.getReport(defaultId);
      setReport(rep);
    }
    setLoading(false);
  };

  useEffect(() => {
    let active = true;
    const load = async () => {
      setLoading(true);
      const { incidents: data } = await IncidentService.getAllIncidents();
      if (!active) return;
      setIncidents(data);
      if (data.length > 0) {
        const defaultId = data[0].incidentId;
        setSelectedIncidentId(defaultId);
        const { report: rep } = await IncidentService.getReport(defaultId);
        if (active) setReport(rep);
      }
      if (active) setLoading(false);
    };
    load();
    return () => {
      active = false;
    };
  }, []);

  const handleSelectIncident = async (id: string) => {
    setSelectedIncidentId(id);
    setLoading(true);
    const { report: rep } = await IncidentService.getReport(id);
    setReport(rep);
    setLoading(false);
  };

  const generateMarkdownReport = (rep: IncidentReport): string => {
    return `# TrueForge Incident Execution Report: ${rep.incidentId}

**Title:** ${rep.title}  
**Service:** ${rep.serviceName} | **Environment:** ${rep.environment} | **Severity:** ${rep.severity}  
**Final Status:** ${rep.finalStatus}  
**Duration:** ${rep.executionDuration} | **Generated At:** ${rep.generatedAt}  

---

## 1. LLM Diagnosis & Root Cause
* **Probable Cause:** ${rep.diagnosis.probableCause}
* **Confidence Score:** ${(rep.diagnosis.confidenceScore * 100).toFixed(0)}%
* **Matched Runbook:** ${rep.selectedRunbook.title} (\`${rep.selectedRunbook.id}\`)

---

## 2. Execution Log Steps
${rep.executionSteps
  .map(
    (s) => `- **[${s.type}]** ${s.stepName} — Status: \`${s.status}\` (${s.durationMs || 0}ms)`
  )
  .join('\n')}

---

## 3. Human Approval Gate
* **Approval Required:** ${rep.approvalStatus.approvalRequired ? 'YES' : 'NO'}
* **Gate Status:** ${rep.approvalStatus.status || 'N/A'}
* **Approved/Rejected By:** ${rep.approvalStatus.approvedBy || rep.approvalStatus.rejectionReason || 'N/A'}

---

## 4. Remediation & Verification
* **Action Executed:** ${rep.remediationPerformed?.action || 'None'}
* **Remediation Result:** ${rep.remediationPerformed?.success ? 'SUCCESS' : 'N/A'}
* **Closed-Loop Verification:** ${rep.verificationResult?.status || 'N/A'} (${rep.verificationResult?.details || 'N/A'})

*Report generated by TrueForge Agent Harness v0.2.0*
`;
  };

  const handleDownload = (format: 'markdown' | 'json') => {
    if (!report) return;
    let content = '';
    let filename = `incident-report-${report.incidentId}`;
    let mimeType = 'text/plain';

    if (format === 'markdown') {
      content = generateMarkdownReport(report);
      filename += '.md';
      mimeType = 'text/markdown';
    } else {
      content = JSON.stringify(report, null, 2);
      filename += '.json';
      mimeType = 'application/json';
    }

    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleCopyMarkdown = () => {
    if (!report) return;
    const md = generateMarkdownReport(report);
    navigator.clipboard.writeText(md);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="space-y-8">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-slate-800 pb-5">
        <div>
          <h1 className="text-2xl font-extrabold text-slate-100 tracking-tight">Incident Reports & Auditing</h1>
          <p className="text-xs text-slate-400 mt-1">
            Structured post-incident execution logs, approval audit trails, and verification export.
          </p>
        </div>

        {report && (
          <div className="flex items-center gap-2">
            <button
              onClick={() => handleDownload('markdown')}
              className="bg-indigo-600 hover:bg-indigo-500 text-white font-semibold text-xs py-2.5 px-3.5 rounded-lg flex items-center gap-1.5 transition-all shadow-md shadow-indigo-600/30"
            >
              <Download className="w-3.5 h-3.5" />
              <span>Export Markdown</span>
            </button>
            <button
              onClick={() => handleDownload('json')}
              className="bg-slate-800 hover:bg-slate-700 text-slate-200 font-semibold text-xs py-2.5 px-3.5 rounded-lg flex items-center gap-1.5 transition-colors border border-slate-700"
            >
              <Download className="w-3.5 h-3.5 text-indigo-400" />
              <span>Export JSON</span>
            </button>
          </div>
        )}
      </div>

      {/* Main Container */}
      <div className="grid grid-cols-1 lg:grid-cols-4 gap-6">
        {/* Left Column: Selector */}
        <div className="lg:col-span-1 p-4 rounded-xl border border-slate-800 bg-slate-900/80 space-y-3">
          <div className="flex items-center justify-between border-b border-slate-800 pb-2">
            <h3 className="text-xs font-bold text-slate-300 uppercase tracking-wider">Select Incident</h3>
            <button onClick={fetchReportsList} title="Refresh list">
              <RefreshCw className={`w-3.5 h-3.5 text-slate-400 ${loading ? 'animate-spin' : ''}`} />
            </button>
          </div>

          <div className="space-y-1.5 max-h-96 overflow-y-auto pr-1">
            {incidents.map((inc) => (
              <button
                key={inc.incidentId}
                onClick={() => handleSelectIncident(inc.incidentId)}
                className={`w-full text-left p-3 rounded-lg border text-xs transition-all ${
                  selectedIncidentId === inc.incidentId
                    ? 'bg-indigo-600/15 border-indigo-500/40 text-indigo-300 font-semibold'
                    : 'bg-slate-950/60 border-slate-800/80 text-slate-400 hover:bg-slate-800/60 hover:text-slate-200'
                }`}
              >
                <div className="flex items-center justify-between">
                  <span className="font-mono font-bold">{inc.incidentId}</span>
                  <span className="text-[10px] uppercase font-bold">{inc.status}</span>
                </div>
                <p className="text-[11px] truncate mt-1 text-slate-300">{inc.intake.title}</p>
              </button>
            ))}
          </div>
        </div>

        {/* Right Column: Report Viewer */}
        <div className="lg:col-span-3 space-y-4">
          {/* View Tabs */}
          <div className="flex items-center justify-between border-b border-slate-800 pb-3">
            <div className="flex items-center gap-2 bg-slate-950 p-1 rounded-lg border border-slate-800">
              <button
                onClick={() => setActiveTab('VISUAL')}
                className={`px-3 py-1.5 rounded-md text-xs font-semibold transition-all ${
                  activeTab === 'VISUAL'
                    ? 'bg-indigo-600 text-white shadow-sm'
                    : 'text-slate-400 hover:text-slate-200'
                }`}
              >
                Executive Visual Report
              </button>
              <button
                onClick={() => setActiveTab('MARKDOWN')}
                className={`px-3 py-1.5 rounded-md text-xs font-semibold transition-all ${
                  activeTab === 'MARKDOWN'
                    ? 'bg-indigo-600 text-white shadow-sm'
                    : 'text-slate-400 hover:text-slate-200'
                }`}
              >
                Markdown View
              </button>
              <button
                onClick={() => setActiveTab('JSON')}
                className={`px-3 py-1.5 rounded-md text-xs font-semibold transition-all ${
                  activeTab === 'JSON'
                    ? 'bg-indigo-600 text-white shadow-sm'
                    : 'text-slate-400 hover:text-slate-200'
                }`}
              >
                Structured JSON
              </button>
            </div>

            {report && (
              <button
                onClick={handleCopyMarkdown}
                className="text-xs text-slate-400 hover:text-indigo-400 flex items-center gap-1 font-mono transition-colors"
              >
                {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                <span>{copied ? 'Copied MD!' : 'Copy MD'}</span>
              </button>
            )}
          </div>

          {!report ? (
            <div className="p-12 text-center text-slate-400 text-xs">No report loaded.</div>
          ) : activeTab === 'VISUAL' ? (
            /* Visual Executive Report View */
            <div className="p-6 rounded-2xl border border-slate-800 bg-slate-900/80 backdrop-blur-md space-y-6 text-xs">
              {/* Report Header */}
              <div className="flex items-start justify-between border-b border-slate-800 pb-4">
                <div>
                  <div className="flex items-center gap-2">
                    <FileText className="w-5 h-5 text-indigo-400" />
                    <h2 className="text-lg font-bold text-slate-100">{report.title}</h2>
                  </div>
                  <p className="text-slate-400 font-mono mt-1">
                    ID: <strong className="text-indigo-400">{report.incidentId}</strong> | Service:{' '}
                    <strong className="text-slate-200">{report.serviceName}</strong> | Env:{' '}
                    <strong className="text-slate-200">{report.environment}</strong>
                  </p>
                </div>
                <div className="text-right">
                  <span className="px-3 py-1 rounded-full text-xs font-bold uppercase bg-emerald-500/20 text-emerald-400 border border-emerald-500/40">
                    {report.finalStatus}
                  </span>
                  <p className="text-[11px] text-slate-500 mt-1 font-mono">Duration: {report.executionDuration}</p>
                </div>
              </div>

              {/* Diagnosis Summary */}
              <div className="space-y-2">
                <h3 className="font-bold text-slate-200 uppercase tracking-wider text-[11px]">1. AI Diagnosis & Runbook</h3>
                <div className="bg-slate-950 p-3.5 rounded-xl border border-slate-800 space-y-2">
                  <p className="font-mono text-indigo-300">{report.diagnosis.probableCause}</p>
                  <p className="text-slate-400">
                    Matched Runbook: <strong className="text-slate-200">{report.selectedRunbook.title} ({report.selectedRunbook.id})</strong>
                  </p>
                </div>
              </div>

              {/* Execution Steps */}
              <div className="space-y-2">
                <h3 className="font-bold text-slate-200 uppercase tracking-wider text-[11px]">2. Execution Steps Audit Log</h3>
                <div className="space-y-2">
                  {report.executionSteps.map((s) => (
                    <div key={s.stepId} className="p-3 rounded-lg bg-slate-950 border border-slate-800 flex items-center justify-between">
                      <div className="flex items-center gap-2 font-mono">
                        <Terminal className="w-3.5 h-3.5 text-indigo-400" />
                        <span className="font-bold text-slate-200">{s.stepName}</span>
                      </div>
                      <div className="flex items-center gap-3">
                        <span className="text-[10px] text-slate-500">{s.durationMs || 0}ms</span>
                        <span className="px-2 py-0.5 rounded text-[10px] uppercase font-bold bg-emerald-500/10 text-emerald-400 border border-emerald-500/30">
                          {s.status}
                        </span>
                      </div>
                    </div>
                  ))}
                </div>
              </div>

              {/* Approval Audit */}
              <div className="space-y-2">
                <h3 className="font-bold text-slate-200 uppercase tracking-wider text-[11px]">3. Human Approval Audit</h3>
                <div className="bg-slate-950 p-3.5 rounded-xl border border-slate-800 space-y-1">
                  <p className="text-slate-300">
                    Gate Status: <strong className="text-emerald-400">{report.approvalStatus.status || 'N/A'}</strong>
                  </p>
                  {report.approvalStatus.approvedBy && (
                    <p className="text-slate-400">Approved by: <strong className="text-slate-200">{report.approvalStatus.approvedBy}</strong></p>
                  )}
                </div>
              </div>

              {/* Remediation & Verification */}
              <div className="space-y-2">
                <h3 className="font-bold text-slate-200 uppercase tracking-wider text-[11px]">4. Closed-Loop Verification</h3>
                <div className="bg-slate-950 p-3.5 rounded-xl border border-slate-800 text-emerald-300 font-mono">
                  {report.verificationResult?.details || 'Verification completed successfully.'}
                </div>
              </div>
            </div>
          ) : activeTab === 'MARKDOWN' ? (
            /* Markdown Raw View */
            <div className="bg-slate-950 p-4 rounded-xl border border-slate-800 font-mono text-xs text-indigo-200 overflow-x-auto whitespace-pre-wrap">
              {generateMarkdownReport(report)}
            </div>
          ) : (
            /* JSON Raw View */
            <div className="bg-slate-950 p-4 rounded-xl border border-slate-800 font-mono text-xs text-emerald-300 overflow-x-auto">
              <pre>{JSON.stringify(report, null, 2)}</pre>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
